export default {
  PRIMARY_COLOR: "black",
  SECONDARY_COLOR: "white",
  SUCCESS_GREEN: "#8bed84",
  FAIL_RED: "#FF4136",
  FONT_SIZE_XS: 12,
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_MEDIUM: 16,
  FONT_SIZE_LARGE: 18,
  FONT_SIZE_XL: 24,
  FONT_SIZE_XXL: 32,
  FONT_SIZE_XXXL: 48,
  FONT_WEIGHT_LIGHT: "200",
  FONT_WEIGHT_MEDIUM: "500",
  FONT_WEIGHT_BOLD: "700",
  SCREEN_CONTAINER_PADDING: 20
};
